// src\app\doctors\models\api-docor.ts
export interface ApiDocor {
  oid: string,
  userId: string,
  firstNameAr?: string,
  middleNameAr?: string,
  lastNameAr?: string,
  firstNameEn?: string,
  middleNameEn?: string,
  lastNameEn?: string,
  genderId?: string,
  username: string,
  doctorFullName: string,
  licenseNumber: string,
  licenseTypeId?: string,
  licenseIssueDate?: string,
  licenseExpiryDate?: string,
  specialtyId: string,
  subSpecialtyId?: string,
  specialtyNameEn: string,
  specialtyNameAr: string,
  departmentLookupId: string,
  departmentId?: string,
  departmentName: string,
  mobile?: string,
  phone?: string,
  email?: string,
  yearsOfExperience?: number,
  consultationFee?: number,
  branchId: string,
  branchName: string,
  nphiesProviderId: string | null,
  nphiesLicenseNumber?: string,
  isNphiesEnabled: boolean,
  isActive: boolean,
  createdAt: string,
  updatedAt: string
}
